apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump}}
  description: Springboot REST Framework OpenAPI
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - rest
spec:
  type: openapi
  lifecycle: development
  owner: ${{values.owner | dump}}
  definition: |
    {
      "openapi": "3.0.1",
      "info": {
        "title": "OpenAPI definition",
        "version": "v0"
      },
      "servers": [
        {
          "url": "http://localhost:8080",
          "description": "Generated server url"
        }
      ],
      "paths": {
        "/hello": {
          "get": {
            "tags": [
              "greeting-controller"
            ],
            "operationId": "greeting",
            "responses": {
              "200": {
                "description": "OK",
                "content": {
                  "*/*": {
                    "schema": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "components": {}
    }
