apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.artifact_id}}
  labels:
    backstage.io/kubernetes-id: ${{values.artifact_id}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${{values.artifact_id}}
  template:
    metadata:
      labels:
        app: ${{values.artifact_id}}
        backstage.io/kubernetes-id: ${{values.artifact_id}}
    spec:
      containers:
        - name: ${{values.artifact_id}}
          image: sahanan05/${{values.artifact_id}}:latest
          ports:
            - containerPort: 8080
