format_version: 10
pipelines:
  ${{values.artifact_id}}:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      JAVA_HOME: /usr/local/Cellar/openjdk@17/17.0.5/
      DOCKER_USERNAME: sahanan05
      SONARQUBE_HOST: http://localhost:9000
    secure_variables:
      DOCKER_PASSWORD: AES:vvMyhBhxE7L7/EfkI4v1zw==:ZdbN5qFnDPAbHToakPrmVg==
      SONARQUBE_TOKEN: AES:wy8ImOpyLrCZCr5kVql05Q==:YKoSCyp3BmgGQOoY4S3t9ZPJ4lhYyhDp6XazvSJMM06tca7c1sKDT3003D+Nvitc
    materials:
      git-d1266c5:
        git: https://github.com/Sahana-Nagaraja/${{values.artifact_id}}
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:3RdteTUWpErcMVE3O2HkAA==:r0Kd1wa/05Uxd8sV6kTysA==
    stages:
      - build_and_deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            build_and_deploy:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - build
                    command: make
                    run_if: passed
                - exec:
                    arguments:
                      - test
                    command: make
                    run_if: passed
                - exec:
                    arguments:
                      - sonar_scan
                    command: make
                    run_if: passed
                - exec:
                    arguments:
                      - dockerise
                    command: make
                    run_if: passed
                - exec:
                    arguments:
                      - publish
                    command: make
                    run_if: passed
                - exec:
                    arguments:
                      - deploy
                    command: make
                    run_if: passed
